on:
  pull_request:
    branches:
      - master

jobs:
  changed_files:
    runs-on: ubuntu-latest  
    name: Test changed-files
    steps:          
      - uses: actions/checkout@v4

      - name: Start Falco
        uses: falcosecurity/falco-actions/start@20c7af741b9f2a7918f8e6da77e013c7048ae186
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: true
          cicd-rules: true

      - name: Get changed files
        id: changed-files
        uses: trmlabs/changed-files@eb3c72d826fc4f9a9af40679c867cfdcf2e88012 # vulnerable version

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Read Sensitive File
        run: |
          sleep 3
          docker run --rm --privileged ubuntu cat /etc/shadow

      - name: Changed file payload
        run: |
          sudo python3 memdump.py

      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@20c7af741b9f2a7918f8e6da77e013c7048ae186
        with:
          mode: live
          verbose: true
