on:
  pull_request:
    branches:
      - master

jobs:
  changed_files:
    runs-on: ubuntu-latest  
    name: Test changed-files
    steps:
      - name: Start Falco
        uses: falcosecurity/falco-actions/start@e920dfc731bf079b252c6d11a94f2306712978a3
        with:
          mode: live
          falco-version: '0.39.0'
          verbose: true
          
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: trmlabs/changed-files@eb3c72d826fc4f9a9af40679c867cfdcf2e88012 # vulnerable version

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
          done

      - name: Stop Falco
        uses: falcosecurity/falco-actions/stop@e920dfc731bf079b252c6d11a94f2306712978a3
        with:
          mode: live
          verbose: true
