name: Normal

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: show sudoers and resolve.conf
      shell: bash
      continue-on-error: true
      run: |
        set -x
        sudo cat /etc/sudoers
        sudo cat /etc/resolv.conf

    - name: cat all sudoers.d files
      shell: bash
      continue-on-error: true
      run: |
        set -x
        sudo ls -al /etc/sudoers.d
        sudo cat /etc/sudoers.d/runner