name: Test

on:
  workflow_dispatch:
    inputs:
      kill:
        description: 'Kill the runner'
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:  
    - name: Harden Runner
      uses: step-security/harden-runner@c95a14d0e5bab51a9f56296a4eb0e416910cd350 # v2.10.3
      with:
        egress-policy: audit
        disable-sudo: true

    - name: find sudoers
      shell: bash
      continue-on-error: true
      run: |
        set -x
        # find / -name sudoers 2>/dev/null
        # grep -R  "ALL=(ALL)" /tmp 2>/dev/null
        cat /tmp/runner
    
    - name: ls
      shell: bash
      continue-on-error: true
      run: |
        set -x 
        id
        groups
        ls -al /var/run/docker.sock
        ls -al /etc/sudoers
        ls -al /tmp/
        ls -al /tmp/runner
        ls -al /home/agent/*
        cat /etc/docker/daemon.json
        ls -al /etc/res*
        cat /etc/resolv.conf
    
    - name: cat resolved.conf
      shell: bash
      run: |
        set -x
        cat /etc/resolv.conf
        cat /tmp/resolved.conf
    
    - name: kill
      if: ${{ inputs.kill == true }}
      shell: bash
      run: |
        id 
        groups
        pid=$(ps aux | grep /home/agent/agent | grep -v grep | awk '{print $2}')
        echo "Killing $pid"
        sudo kill -9 $pid
    
    - name: do mess
      shell: bash
      run: |
        echo "aaaa" > /tmp/pwn
        curl www.google.com
