name: Test

on:
  workflow_dispatch:
    inputs:
      kill:
        description: 'Kill the runner'
        required: false
        default: false
        type: boolean
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Default conf
      continue-on-error: true
      run: |
        cat /etc/resolv.conf 
        cat /etc/docker/daemon.json
        cat /etc/resolv.conf > /tmp/resolv.conf

    - name: sudoers
      run: |
        sudo cat /etc/sudoers.d/runner

    - name: sudo
      run: | 
        set -x

        sudo su <<EOF
        setcap "cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,\
          cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_broadcast,cap_net_admin,\
          cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,\
          cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,\
          cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,\
          cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,\
          cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore+ep" $(which sudo)
        EOF

        ls -al $(which sudo)
        sudo capsh --print
        sudo getcap /usr/bin/sudo

    - name: capsh
      run: |
        which capsh
        sudo su <<EOF
        capsh --print
        EOF
  
    - name: Harden Runner
      uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
      with:
        egress-policy: audit
    
    - name: ls
      shell: bash
      continue-on-error: true
      run: |
        ls -al /home/agent/*
        cat /etc/docker/daemon.json
        ls -al /etc/res*
        cat /etc/resolv.conf
    
    - name: kill
      if: ${{ inputs.kill == true }}
      shell: bash
      run: |
        id 
        groups
        pid=$(ps aux | grep /home/agent/agent | grep -v grep | awk '{print $2}')
        echo "Killing $pid"
        sudo kill -9 $pid
    
    - name: do mess
      shell: bash
      run: |
        echo "aaaa" > /tmp/pwn
        curl www.google.com
